version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/modern_web_app
      - NEXTAUTH_SECRET=BLT0SfGY2cPf1QaDJmhpkRHlpBKpRz0YLErJymjilCQ=
      - NEXTAUTH_URL=http://localhost:3000
      - REDIS_URL=redis://redis:6379
      # Stripe Configuration (placeholder keys for demo - replace with real keys in production)
      - STRIPE_SECRET_KEY=sk_test_placeholder_secret_key_replace_in_production
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_placeholder_publishable_key_replace_in_production
      # Application Configuration
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
      - NEXT_PUBLIC_APP_NAME=Modern Web App Dashboard
      - NEXT_PUBLIC_APP_VERSION=1.0.0
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: modern_web_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: 